// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Catalogue struct {
	IDUser int32         `json:"id_user"`
	IDGame int32         `json:"id_game"`
	Score  sql.NullInt32 `json:"score"`
	Status string        `json:"status"`
}

type Library struct {
	IDGame      int32          `json:"id_game"`
	Title       string         `json:"title"`
	Description string         `json:"description"`
	AvgScore    sql.NullString `json:"avg_score"`
}

type User struct {
	IDUser   int32  `json:"id_user"`
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}
