// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const createGame = `-- name: CreateGame :one
INSERT INTO Library (title, description)
VALUES ($1, $2)
RETURNING id_game
`

type CreateGameParams struct {
	Title       string `json:"title"`
	Description string `json:"description"`
}

// LIBRARY
func (q *Queries) CreateGame(ctx context.Context, arg CreateGameParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, createGame, arg.Title, arg.Description)
	var id_game int32
	err := row.Scan(&id_game)
	return id_game, err
}

const createRecord = `-- name: CreateRecord :exec
INSERT INTO Catalogue (id_user, id_game, score, status)
VALUES ($1, $2, $3, $4)
`

type CreateRecordParams struct {
	IDUser int32         `json:"id_user"`
	IDGame int32         `json:"id_game"`
	Score  sql.NullInt32 `json:"score"`
	Status string        `json:"status"`
}

// CATALOGUE
func (q *Queries) CreateRecord(ctx context.Context, arg CreateRecordParams) error {
	_, err := q.db.ExecContext(ctx, createRecord,
		arg.IDUser,
		arg.IDGame,
		arg.Score,
		arg.Status,
	)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO Users (name, email, password)
VALUES ($1, $2, $3)
RETURNING id_user
`

type CreateUserParams struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

// USERS
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Name, arg.Email, arg.Password)
	var id_user int32
	err := row.Scan(&id_user)
	return id_user, err
}

const deleteGame = `-- name: DeleteGame :exec
DELETE FROM Library
WHERE id_game = $1
`

func (q *Queries) DeleteGame(ctx context.Context, idGame int32) error {
	_, err := q.db.ExecContext(ctx, deleteGame, idGame)
	return err
}

const deleteRecord = `-- name: DeleteRecord :exec
DELETE FROM Catalogue
WHERE id_user = $1 AND id_game = $2
`

type DeleteRecordParams struct {
	IDUser int32 `json:"id_user"`
	IDGame int32 `json:"id_game"`
}

func (q *Queries) DeleteRecord(ctx context.Context, arg DeleteRecordParams) error {
	_, err := q.db.ExecContext(ctx, deleteRecord, arg.IDUser, arg.IDGame)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM Users
WHERE id_user = $1
`

func (q *Queries) DeleteUser(ctx context.Context, idUser int32) error {
	_, err := q.db.ExecContext(ctx, deleteUser, idUser)
	return err
}

const getGame = `-- name: GetGame :one
SELECT id_game, title, description, avg_score
FROM Library
WHERE id_game = $1
`

func (q *Queries) GetGame(ctx context.Context, idGame int32) (Library, error) {
	row := q.db.QueryRowContext(ctx, getGame, idGame)
	var i Library
	err := row.Scan(
		&i.IDGame,
		&i.Title,
		&i.Description,
		&i.AvgScore,
	)
	return i, err
}

const getRecord = `-- name: GetRecord :one
SELECT id_user, id_game, score, status
FROM Catalogue
WHERE id_user = $1 AND id_game = $2
`

type GetRecordParams struct {
	IDUser int32 `json:"id_user"`
	IDGame int32 `json:"id_game"`
}

func (q *Queries) GetRecord(ctx context.Context, arg GetRecordParams) (Catalogue, error) {
	row := q.db.QueryRowContext(ctx, getRecord, arg.IDUser, arg.IDGame)
	var i Catalogue
	err := row.Scan(
		&i.IDUser,
		&i.IDGame,
		&i.Score,
		&i.Status,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id_user, name, email
FROM Users
WHERE id_user = $1
`

type GetUserRow struct {
	IDUser int32  `json:"id_user"`
	Name   string `json:"name"`
	Email  string `json:"email"`
}

func (q *Queries) GetUser(ctx context.Context, idUser int32) (GetUserRow, error) {
	row := q.db.QueryRowContext(ctx, getUser, idUser)
	var i GetUserRow
	err := row.Scan(&i.IDUser, &i.Name, &i.Email)
	return i, err
}

const lisRecord = `-- name: LisRecord :many
SELECT id_user, id_game, score, status
FROM Catalogue
WHERE id_user = $1
ORDER BY (id_user, id_game)
`

func (q *Queries) LisRecord(ctx context.Context, idUser int32) ([]Catalogue, error) {
	rows, err := q.db.QueryContext(ctx, lisRecord, idUser)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Catalogue
	for rows.Next() {
		var i Catalogue
		if err := rows.Scan(
			&i.IDUser,
			&i.IDGame,
			&i.Score,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGames = `-- name: ListGames :many
SELECT id_game, title, description, avg_score
FROM Library
ORDER BY id_game
`

func (q *Queries) ListGames(ctx context.Context) ([]Library, error) {
	rows, err := q.db.QueryContext(ctx, listGames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Library
	for rows.Next() {
		var i Library
		if err := rows.Scan(
			&i.IDGame,
			&i.Title,
			&i.Description,
			&i.AvgScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id_user, name, email
FROM Users
ORDER BY id_user
`

type ListUsersRow struct {
	IDUser int32  `json:"id_user"`
	Name   string `json:"name"`
	Email  string `json:"email"`
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(&i.IDUser, &i.Name, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGame = `-- name: UpdateGame :exec
UPDATE Library
SET title = $2, description =$3
WHERE id_game = $1
`

type UpdateGameParams struct {
	IDGame      int32  `json:"id_game"`
	Title       string `json:"title"`
	Description string `json:"description"`
}

func (q *Queries) UpdateGame(ctx context.Context, arg UpdateGameParams) error {
	_, err := q.db.ExecContext(ctx, updateGame, arg.IDGame, arg.Title, arg.Description)
	return err
}

const updateRecord = `-- name: UpdateRecord :exec
UPDATE Catalogue
SET score = $3, status =$4
WHERE id_user = $1 AND id_game = $2
`

type UpdateRecordParams struct {
	IDUser int32         `json:"id_user"`
	IDGame int32         `json:"id_game"`
	Score  sql.NullInt32 `json:"score"`
	Status string        `json:"status"`
}

func (q *Queries) UpdateRecord(ctx context.Context, arg UpdateRecordParams) error {
	_, err := q.db.ExecContext(ctx, updateRecord,
		arg.IDUser,
		arg.IDGame,
		arg.Score,
		arg.Status,
	)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE Users
SET name = $2, email =$3
WHERE id_user = $1
`

type UpdateUserParams struct {
	IDUser int32  `json:"id_user"`
	Name   string `json:"name"`
	Email  string `json:"email"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser, arg.IDUser, arg.Name, arg.Email)
	return err
}
