-- Created by Redgate Data Modeler (https://datamodeler.redgate-platform.com/)
-- Last modification date: 2026-09-14 16:18:22.95

-- tables
-- Table: Catalogue
CREATE TABLE Catalogue (
    id_user int  NOT NULL,
    id_game int  NOT NULL,
    score int,
    status varchar(20) NOT NULL,
    CONSTRAINT check_score CHECK (score BETWEEN 1 AND 5) NOT DEFERRABLE INITIALLY IMMEDIATE,
    CONSTRAINT Catalogue_pk PRIMARY KEY (id_game,id_user)
);

-- Table: Library
CREATE TABLE Library (
    id_game int  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    title varchar(255)  NOT NULL,
    description text  NOT NULL,
    avg_score decimal(3,2) DEFAULT 0,
    CONSTRAINT Library_pk PRIMARY KEY (id_game)
);

-- Table: Users
CREATE TABLE Users (
    id_user int  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name varchar(255)  NOT NULL,
    email varchar(255)  NOT NULL,
    password varchar(255)  NOT NULL,
    CONSTRAINT Users_unique_email UNIQUE (email) NOT DEFERRABLE  INITIALLY IMMEDIATE,
    CONSTRAINT Users_pk PRIMARY KEY (id_user)
);

-- foreign keys
-- Reference: Catalogue_Library (table: Catalogue)
ALTER TABLE Catalogue ADD CONSTRAINT Catalogue_Library
    FOREIGN KEY (id_game)
    REFERENCES Library (id_game)
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: Catalogue_Users (table: Catalogue)
ALTER TABLE Catalogue ADD CONSTRAINT Catalogue_Users
    FOREIGN KEY (id_user)
    REFERENCES Users (id_user)
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Functions
-- Función que recalcula el promedio y actualiza la tabla Library
CREATE OR REPLACE FUNCTION update_game_avg_score()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE Library
    SET avg_score = (
        SELECT COALESCE(AVG(score), 0)::decimal(3,2)
        FROM Catalogue
        WHERE id_game = COALESCE(NEW.id_game, OLD.id_game)
    )
    WHERE id_game = COALESCE(NEW.id_game, OLD.id_game);

    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

-- Triggers
-- Trigger asociado a la tabla Catalogue
CREATE TRIGGER trg_update_avg_score
AFTER INSERT OR UPDATE OF score OR DELETE
ON Catalogue
FOR EACH ROW
EXECUTE FUNCTION update_game_avg_score();

-- End of file.